Ermögliche whitelisting spezifischer node modules beim Transpilieren mit Babel  (Case 146461)
webfactory/webfactory-gulp-preset pull request #24
Opened 2022-06-10 12:58 UTC by megatronCGN

Unter Umständen ist es notwendig, Scripte aus dem `node_modules Ordner zu transpilieren, um das JS auf alle unterstützten Browsern lauffähig zu machen. Dieser PR ermöglicht das Whitelisten spezifischer Ordner in der Projekt-eigenen `gulp-config.js`.

2022-06-12 19:29 UTC, polarbirke requested changes, later dismissed
Der "alte" Weg in `scripts.js` sollte die Anpassung auch bekommen – oder ist der so unerwünscht, dass er keine maintenance mehr bekommt…? 😁

PS: Version bump in package.json nicht vergessen, dass passiert mir bei jedem zweiten PR.

2022-06-12 19:29 UTC, polarbirke commented on README.md
> +const { webpack } = require('./node_modules/webfactory-gulp-preset/tasks/webpack');const { styles } = require('./node_modules/webfactory-gulp-preset/tasks/styles');
Umbruch fehlt?

2022-06-12 19:29 UTC, polarbirke commented on README.md
> +    webpack(gulp, $, config);
Das ist eher ein anderer PR? Ich hatte in der Readme bewusst erst mal den alten Weg behalten (Webpack wird weiter unten erklärt), weil die meisten Projekte noch nicht umgestellt sind/waren.

Können wir auch umdrehen, dann sollte der alte Weg vielleicht unten als Alternative erläutert werden?

2022-06-12 19:29 UTC, polarbirke commented on tasks/webpack.js
> +                        exclude: new RegExp('node_modules\\/(?![svelte' + includeModules + '])'),
Wenn das tut was es soll (DSAR/G-BA als Svelte-Projekte getestet?) – go for it!

2022-06-13 06:37 UTC, megatronCGN commented
> Der "alte" Weg in `scripts.js` sollte die Anpassung auch bekommen – oder ist der so unerwünscht, dass er keine maintenance mehr bekommt…? 😁
> 
> PS: Version bump in package.json nicht vergessen, dass passiert mir bei jedem zweiten PR.

`Ye Olde Way` konkateniert ja nur und transpiliert nicht und braucht deswegen die Anpassung nicht.

2022-06-13 08:41 UTC, gnitter submitted a review, later dismissed

2022-06-13 08:41 UTC, gnitter commented on README.md
> +    webpack(gulp, $, config);
Fänd' den zweiten Weg besser. Das umzudrehen und den alten Weg zu erläutern. Dann läuft man hier auch schon mal los 🙂

2022-06-13 09:24 UTC, polarbirke commented
>`Ye Olde Way` konkateniert ja nur und transpiliert nicht und braucht deswegen die Anpassung nicht. 

Not true! https://github.com/webfactory/webfactory-gulp-preset/blob/7b4b42985c251f3fe98d1f2d507954b48934d3cc/tasks/scripts.js#L16

>Mach den Version Bump nicht `npm publish`automatisch?

Öh, nicht dass ich wüsste. Das committed ja keine neue package.json ins Repo.

2022-06-13 11:47 UTC, megatronCGN commented
@polarbirke Warum hast du den Titel auf Englisch übersetzt?

2022-06-13 11:49 UTC, polarbirke commented
Weil wir Open Source auf Englisch dokumentieren und committen :wink:

2022-06-13 11:51 UTC, megatronCGN commented
> Weil wir Open Source auf Englisch dokumentieren und committen 😉

Okay, ergibt Sinn. War mir nicht bewusst.

2022-06-13 11:57 UTC, megatronCGN commented
> > `Ye Olde Way` konkateniert ja nur und transpiliert nicht und braucht deswegen die Anpassung nicht.
> 
> Not true!
> 
> https://github.com/webfactory/webfactory-gulp-preset/blob/7b4b42985c251f3fe98d1f2d507954b48934d3cc/tasks/scripts.js#L16

True dat, aber eine Anpassung ist aus meiner Sicht trotzdem nicht notwendig, weil wir den Pfad nicht excluden. Alle Modules werden in der `gulp-config.js` explizit angegeben und dann transpiliert. Es gibt keinen Grund anzunehmen, dass irgendein Modul dabei ausgelassen wird. Oder übersehe ich etwas?

2022-06-13 12:03 UTC, polarbirke commented
> > > `Ye Olde Way` konkateniert ja nur und transpiliert nicht und braucht deswegen die Anpassung nicht.
> > 
> > 
> > Not true!
> > https://github.com/webfactory/webfactory-gulp-preset/blob/7b4b42985c251f3fe98d1f2d507954b48934d3cc/tasks/scripts.js#L16
> 
> True dat, aber eine Anpassung ist aus meiner Sicht trotzdem nicht notwendig, weil wir den Pfad nicht excluden. Alle Modules werden in der `gulp-config.js` explizit angegeben und dann transpiliert. Es gibt keinen Grund anzunehmen, dass irgendein Modul dabei ausgelassen wird. Oder übersehe ich etwas?

Das klingt total plausibel! :smile: You so right.

2022-06-13 13:12 UTC, merged